# Generated by Django 5.0 on 2023-12-18 14:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('groups', '0003_event_amount'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupStatistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stats', models.CharField(max_length=10000, null=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_info', to='groups.group')),
            ],
        ),
    ]
