# Generated by Django 5.0 on 2023-12-18 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group_statistics', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='groupstatistics',
            name='stats',
        ),
        migrations.AddField(
            model_name='groupstatistics',
            name='accumulated_amount_paid',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=2, max_length=1000000000),
        ),
        migrations.AddField(
            model_name='groupstatistics',
            name='accumulated_amount_paid_by_user',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=2, max_length=1000000000),
        ),
    ]
