# Generated by Django 5.0 on 2023-12-19 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group_statistics', '0002_remove_groupstatistics_stats_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='groupstatistics',
            name='accumulated_amount_paid_by_user',
        ),
        migrations.AddField(
            model_name='groupstatistics',
            name='accumulated_amount_paid_by_users',
            field=models.CharField(default=0, max_length=1000000000),
        ),
        migrations.AddField(
            model_name='groupstatistics',
            name='number_of_members',
            field=models.IntegerField(default=0, max_length=100),
        ),
    ]
