# Generated by Django 5.0 on 2023-12-19 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group_statistics', '0003_remove_groupstatistics_accumulated_amount_paid_by_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupstatistics',
            name='number_of_members',
            field=models.IntegerField(default=0),
        ),
    ]
