# Generated by Django 5.0 on 2023-12-24 17:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_name', models.CharField(max_length=255)),
                ('date_created', models.DateField(blank=True)),
                ('members', models.ManyToManyField(max_length=255, related_name='group_memberships', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(max_length=255)),
                ('event_type', models.CharField(choices=[('Gas', 'Gas'), ('Gifts', 'Gifts'), ('Bills', 'Bills'), ('Electricity', 'Electricity'), ('Energy', 'Energy'), ('Home/Rent/Maintenance', 'Home/Rent/Maintenance'), ('Car expenses', 'Car expenses'), ('Groceries', 'Groceries'), ('Parking', 'Parking'), ('Dinning/Going out', 'Dinning/Going out')], max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('date_created', models.DateField(blank=True)),
                ('paid_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paid_events', to=settings.AUTH_USER_MODEL)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='groups.group')),
            ],
        ),
    ]
