# Generated by Django 5.0 on 2023-12-15 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='group_name',
            new_name='group',
        ),
        migrations.AlterField(
            model_name='event',
            name='event_type',
            field=models.CharField(choices=[('Gas', 'Gas'), ('Bills', 'Bills'), ('Groceries', 'Groceries'), ('Parking', 'Parking'), ('Dinning/Going out', 'Dinning/Going out')], max_length=255),
        ),
    ]
